# Generated by Django 4.2.10 on 2024-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(verbose_name='program_url')),
                ('efirweek', models.DateField(verbose_name='Эфирная неделя')),
                ('channel', models.CharField(max_length=10, verbose_name='Название канала')),
                ('channelid', models.CharField(max_length=10, verbose_name='ID канала')),
                ('updated', models.DateTimeField(verbose_name='Время обновления канала')),
                ('variant', models.CharField(max_length=1, verbose_name='ID канала')),
            ],
            options={
                'unique_together': {('channelid', 'efirweek', 'variant')},
            },
        ),
    ]
